# Generated by Django 3.1.1 on 2020-10-01 10:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('body_text', models.CharField(max_length=2048)),
                ('delay', models.PositiveIntegerField(default=0, help_text='Delay in seconds, max. 60', validators=[django.core.validators.MaxValueValidator(60)])),
                ('status', models.SmallIntegerField(choices=[(1, 'created'), (2, 'scheduled'), (3, 'sent'), (4, 'error sending')], default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_for', models.DateTimeField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
